# Generated by Django 6.0.2 on 2026-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('condo', 'Condo'), ('apartment', 'Apartment'), ('warehouse', 'Warehouse'), ('land', 'Plot of Land')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('owner_direct', models.BooleanField(db_index=True, default=False)),
                ('is_installment_available', models.BooleanField(db_index=True, default=False)),
                ('is_presale', models.BooleanField(db_index=True, default=False)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('area_dimension_text', models.CharField(blank=True, editable=False, max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('township', models.CharField(max_length=50)),
                ('quarter', models.CharField(blank=True, max_length=50)),
                ('road', models.CharField(blank=True, max_length=100)),
                ('landmarks', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('active_buttons', models.JSONField(blank=True, default=dict)),
                ('contact_phone', models.CharField(max_length=20)),
                ('viber_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_boosted', models.BooleanField(db_index=True, default=False)),
                ('is_premium', models.BooleanField(db_index=True, default=False)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
